theme: jekyll-theme-cayman
title: Playlist Analyzer
description: Learn more about Spotify users' Top 100 playlists to find insights on their musical tastes, and generate playlists customized for a user or group of users. 
